<a href="https://colab.research.google.com/github/bigbird999999/NewProject/blob/main/teclov_pandas_ppt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# create Pandas Series

In [ ]:
import pandas as pd

In [ ]:
a = pd.Series([1,2,3,4,5])

In [ ]:
a

,0
0,1
1,2
2,3
3,4
4,5


In [ ]:
type(a)

pandas.core.series.Series

In [ ]:
a[2]

np.int64(3)

In [ ]:
a = pd.Series(['a','b','c'])

In [ ]:
a

,0
0,a
1,b
2,c


In [ ]:
a = pd.date_range(start = '01-01-2018', end = '23-5-2018')

In [ ]:
a

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08',
               '2018-01-09', '2018-01-10',
               ...
               '2018-05-14', '2018-05-15', '2018-05-16', '2018-05-17',
               '2018-05-18', '2018-05-19', '2018-05-20', '2018-05-21',
               '2018-05-22', '2018-05-23'],
              dtype='datetime64[ns]', length=143, freq='D')

In [ ]:
type(a)

pandas.core.indexes.datetimes.DatetimeIndex

# Pandas dataframe

In [ ]:
import numpy as np

In [ ]:
temp = np.random.randint(low = 20, high =100, size = [20,])
name = np.random.choice(['Abhay','Teclov','Geekshub','Ankit'],20)
random = np.random.choice([10,11,13,12,14],20)

In [ ]:
temp

array([28, 43, 67, 76, 80, 91, 90, 61, 71, 29, 40, 66, 91, 90, 46, 41, 48,
       40, 35, 73])

In [ ]:
name

array(['Ankit', 'Ankit', 'Geekshub', 'Abhay', 'Geekshub', 'Abhay',
       'Geekshub', 'Abhay', 'Abhay', 'Ankit', 'Abhay', 'Teclov', 'Abhay',
       'Abhay', 'Geekshub', 'Abhay', 'Teclov', 'Ankit', 'Ankit', 'Teclov'],
      dtype='<U8')

In [ ]:
random

array([12, 10, 14, 11, 10, 12, 12, 10, 14, 13, 11, 10, 10, 10, 13, 12, 13,
       11, 11, 10])

In [ ]:
a = list(zip(temp, name, random))
a

[(np.int64(28), np.str_('Ankit'), np.int64(12)),
 (np.int64(43), np.str_('Ankit'), np.int64(10)),
 (np.int64(67), np.str_('Geekshub'), np.int64(14)),
 (np.int64(76), np.str_('Abhay'), np.int64(11)),
 (np.int64(80), np.str_('Geekshub'), np.int64(10)),
 (np.int64(91), np.str_('Abhay'), np.int64(12)),
 (np.int64(90), np.str_('Geekshub'), np.int64(12)),
 (np.int64(61), np.str_('Abhay'), np.int64(10)),
 (np.int64(71), np.str_('Abhay'), np.int64(14)),
 (np.int64(29), np.str_('Ankit'), np.int64(13)),
 (np.int64(40), np.str_('Abhay'), np.int64(11)),
 (np.int64(66), np.str_('Teclov'), np.int64(10)),
 (np.int64(91), np.str_('Abhay'), np.int64(10)),
 (np.int64(90), np.str_('Abhay'), np.int64(10)),
 (np.int64(46), np.str_('Geekshub'), np.int64(13)),
 (np.int64(41), np.str_('Abhay'), np.int64(12)),
 (np.int64(48), np.str_('Teclov'), np.int64(13)),
 (np.int64(40), np.str_('Ankit'), np.int64(11)),
 (np.int64(35), np.str_('Ankit'), np.int64(11)),
 (np.int64(73), np.str_('Teclov'), np.int64(10))]

In [ ]:
df = pd.DataFrame(data = a,columns=['temp','name','random'])
df

,temp,name,random
0,28,Ankit,12
1,43,Ankit,10
2,67,Geekshub,14
3,76,Abhay,11
4,80,Geekshub,10
5,91,Abhay,12
6,90,Geekshub,12
7,61,Abhay,10
8,71,Abhay,14
9,29,Ankit,13


In [ ]:
df[['temp','name']].values

array([[28, np.str_('Ankit')],
       [43, np.str_('Ankit')],
       [67, np.str_('Geekshub')],
       [76, np.str_('Abhay')],
       [80, np.str_('Geekshub')],
       [91, np.str_('Abhay')],
       [90, np.str_('Geekshub')],
       [61, np.str_('Abhay')],
       [71, np.str_('Abhay')],
       [29, np.str_('Ankit')],
       [40, np.str_('Abhay')],
       [66, np.str_('Teclov')],
       [91, np.str_('Abhay')],
       [90, np.str_('Abhay')],
       [46, np.str_('Geekshub')],
       [41, np.str_('Abhay')],
       [48, np.str_('Teclov')],
       [40, np.str_('Ankit')],
       [35, np.str_('Ankit')],
       [73, np.str_('Teclov')]], dtype=object)

In [ ]:
temp = np.random.randint(low = 20, high =100, size = [20,])
name = np.random.choice(['Abhay','Teclov','Geekshub','Ankit'],20)
random = np.random.choice([10,11,13,12,14],20)

In [ ]:
df = pd.DataFrame({'temp':temp, 'name':name, 'random':random})
df[:5]

,temp,name,random
0,59,Geekshub,10
1,84,Teclov,12
2,50,Ankit,13
3,50,Ankit,13
4,22,Teclov,11


In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head(3)

,temp,name,random
0,59,Geekshub,10
1,84,Teclov,12
2,50,Ankit,13


In [ ]:
df.tail(3)

,temp,name,random
17,80,Abhay,13
18,32,Geekshub,10
19,86,Abhay,12


In [ ]:
df.shape

(20, 3)

In [ ]:
df.values

array([[60, 'Ankit', 13],
       [22, 'Geekshub', 10],
       [38, 'Abhay', 14],
       [84, 'Ankit', 12],
       [82, 'Ankit', 13],
       [45, 'Geekshub', 14],
       [32, 'Abhay', 11],
       [71, 'Geekshub', 10],
       [61, 'Ankit', 14],
       [29, 'Ankit', 14],
       [41, 'Ankit', 12],
       [36, 'Abhay', 12],
       [50, 'Abhay', 10],
       [37, 'Geekshub', 11],
       [59, 'Ankit', 12],
       [38, 'Geekshub', 14],
       [56, 'Geekshub', 11],
       [39, 'Teclov', 12],
       [74, 'Teclov', 10],
       [73, 'Ankit', 11]], dtype=object)

In [ ]:
df.name

,name
0,Geekshub
1,Teclov
2,Ankit
3,Ankit
4,Teclov
5,Geekshub
6,Geekshub
7,Ankit
8,Geekshub
9,Ankit


In [ ]:
df['name']

0       Teclov
1        Ankit
2       Teclov
3       Teclov
4     Geekshub
5     Geekshub
6        Abhay
7     Geekshub
8     Geekshub
9     Geekshub
10       Ankit
11       Abhay
12      Teclov
13       Ankit
14      Teclov
15       Ankit
16       Abhay
17       Ankit
18      Teclov
19    Geekshub
Name: name, dtype: object

In [ ]:
df["temp"].describe()

,temp
count,20.000000
mean,57.900000
std,21.479243
min,22.000000
25%,43.500000
50%,54.000000
75%,80.000000
max,97.000000


In [ ]:
df[['temp','random']].describe()

,temp,random
count,20.000000,20.000000
mean,57.900000,12.000000
std,21.479243,1.169795
min,22.000000,10.000000
25%,43.500000,11.000000
50%,54.000000,12.000000
75%,80.000000,13.000000
max,97.000000,14.000000


In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   temp    20 non-null     int64 
 1   name    20 non-null     object
 2   random  20 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 612.0+ bytes


In [ ]:
df['name'].value_counts()


,count
name,
Geekshub,10
Teclov,4
Ankit,4
Abhay,2


In [ ]:
df

,temp,name,random
0,59,Geekshub,10
1,84,Teclov,12
2,50,Ankit,13
3,50,Ankit,13
4,22,Teclov,11
5,45,Geekshub,11
6,58,Geekshub,12
7,69,Ankit,10
8,64,Geekshub,13
9,97,Ankit,13


In [ ]:
df.set_index('temp',inplace=True)

In [ ]:
df

,name,random
temp,,
59,Geekshub,10
84,Teclov,12
50,Ankit,13
50,Ankit,13
22,Teclov,11
45,Geekshub,11
58,Geekshub,12
69,Ankit,10
64,Geekshub,13


In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

,temp,name,random
0,59,Geekshub,10
1,84,Teclov,12
2,50,Ankit,13
3,50,Ankit,13
4,22,Teclov,11
5,45,Geekshub,11
6,58,Geekshub,12
7,69,Ankit,10
8,64,Geekshub,13
9,97,Ankit,13


In [ ]:
df.set_index("temp",inplace=True)

In [ ]:
df

,name,random
temp,,
59,Geekshub,10
84,Teclov,12
50,Ankit,13
50,Ankit,13
22,Teclov,11
45,Geekshub,11
58,Geekshub,12
69,Ankit,10
64,Geekshub,13


In [ ]:
df.sort_index(axis =0, ascending=False)

,name,random
temp,,
97,Ankit,13
86,Abhay,12
84,Teclov,12
82,Geekshub,14
80,Geekshub,12
80,Abhay,13
69,Ankit,10
64,Geekshub,13
59,Geekshub,10


In [ ]:
df.values

array([['Geekshub', 10],
       ['Teclov', 12],
       ['Ankit', 13],
       ['Ankit', 13],
       ['Teclov', 11],
       ['Geekshub', 11],
       ['Geekshub', 12],
       ['Ankit', 10],
       ['Geekshub', 13],
       ['Ankit', 13],
       ['Teclov', 13],
       ['Geekshub', 12],
       ['Geekshub', 14],
       ['Geekshub', 12],
       ['Geekshub', 12],
       ['Teclov', 11],
       ['Geekshub', 13],
       ['Abhay', 13],
       ['Geekshub', 10],
       ['Abhay', 12]], dtype=object)

In [ ]:
df.sort_values(by ='random', ascending = False)

,name,random
temp,,
54,Abhay,14
93,Ankit,14
34,Abhay,14
21,Geekshub,13
90,Teclov,13
46,Geekshub,13
54,Geekshub,13
86,Abhay,13
86,Geekshub,12


In [ ]:
df.drop(['random'], axis =1)


,name
temp,
23,Teclov
80,Abhay
67,Abhay
90,Teclov
87,Teclov
46,Geekshub
71,Teclov
82,Geekshub
81,Ankit


In [ ]:
df.head()

,name,random
temp,,
59,Geekshub,10
84,Teclov,12
50,Ankit,13
50,Ankit,13
22,Teclov,11


In [ ]:
df.iloc[[0,2]]

,name,random
temp,,
59,Geekshub,10
50,Ankit,13


In [ ]:
df.iloc[1:3,1] #iloc[start:last-1:step,start:last-1,step] always use its own indexing system to rows and columns.

,random
temp,
84,12
50,13


In [ ]:
df.iloc[[True,True,False,True]]

IndexError: ignored

In [ ]:
df.head()

,name,random
temp,,
59,Geekshub,10
84,Teclov,12
50,Ankit,13
50,Ankit,13
22,Teclov,11


In [ ]:
df.loc[84:50,:]

,name,random
temp,,
84,Teclov,12
50,Ankit,13
50,Ankit,13


In [ ]:
df.loc[[84,50,22]]

,name,random
temp,,
84,Teclov,12
50,Ankit,13
50,Ankit,13
22,Teclov,11


In [ ]:
df.loc[[50,22],'name':'random']

,name,random
temp,,
50,Ankit,13
50,Ankit,13
22,Teclov,11


In [ ]:
df.loc[[True, True, False, True]]

,name,random
temp,,
39,Teclov,13
84,Ankit,10
53,Teclov,11


In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

,temp,name,random
0,59,Geekshub,10
1,84,Teclov,12
2,50,Ankit,13
3,50,Ankit,13
4,22,Teclov,11
5,45,Geekshub,11
6,58,Geekshub,12
7,69,Ankit,10
8,64,Geekshub,13
9,97,Ankit,13


In [ ]:
df[df["name"]=="Geekshub"][["temp","random"]]

,temp,random
0,59,10
5,45,11
6,58,12
8,64,13
11,38,12
12,82,14
13,80,12
14,44,12
16,29,13
18,32,10


In [ ]:
df.loc[(df.random > 13) | (df.random == 10),:]

,temp,name,random
0,59,Geekshub,10
7,69,Ankit,10
12,82,Geekshub,14
18,32,Geekshub,10


In [ ]:
# Merging & concat
d1 = pd.DataFrame([['a', 1], ['b', 2]],columns=['col1', 'number'])
d2 = pd.DataFrame([['c', 3, 'lion'], ['d', 4, 'tiger']],columns=['letter', 'number', 'animal'])

In [ ]:
d1

,col1,number
0,a,1
1,b,2


In [ ]:
d2

,letter,number,animal
0,c,3,lion
1,d,4,tiger


In [ ]:
pd.concat([d1,d2],axis =0,ignore_index=True)

,col1,number,letter,animal
0,a,1,NaN,NaN
1,b,2,NaN,NaN
2,NaN,3,c,lion
3,NaN,4,d,tiger


In [ ]:
pd.concat([d1,d2],axis=1)

,col1,number,letter,number,animal
0,a,1,c,3,lion
1,b,2,d,4,tiger


In [ ]:
pd.concat([d1,d2], axis =0, ignore_index=True)

,animal,col1,letter,number
0,NaN,a,NaN,1
1,NaN,b,NaN,2
2,lion,NaN,c,3
3,tiger,NaN,d,4


In [ ]:
pd.concat([d2,d1], axis = 1)

,letter,number,animal,city,temperature
0,c,3.0,lion,lucknow,32
1,d,4.0,tiger,kanpur,45
2,NaN,NaN,NaN,agra,30
3,NaN,NaN,NaN,delhi,40


In [ ]:
d1 = pd.DataFrame({
    "city" : ["lucknow","kanpur","agra","delhi"],
    "temperature" : [32,45,30,40]
})

In [ ]:
d1

,city,temperature
0,lucknow,32
1,kanpur,45
2,agra,30
3,delhi,40


In [ ]:
d2 = pd.DataFrame({
    "city" : ["delhi","lucknow","kanpur"],
    "humidity" : [68,65,75]
})

In [ ]:
d2

,city,humidity
0,delhi,68
1,lucknow,65
2,kanpur,75


In [ ]:
df = pd.merge(d1,d2, on='city',how='right')

In [ ]:
df

,city,temperature,humidity
0,delhi,40,68
1,lucknow,32,65
2,kanpur,45,75


In [ ]:
pd.merge(d1,d2, on=['city'], how ='outer')

,city,temperature,humidity
0,agra,30,NaN
1,delhi,40,68.0
2,kanpur,45,75.0
3,lucknow,32,65.0


In [ ]:
pd.merge(d1, d2, on =['city'], how='left')

,city,temperature,humidity
0,lucknow,32,65.0
1,kanpur,45,75.0
2,agra,30,NaN
3,delhi,40,68.0


In [ ]:
# dataset from https://github.com/codebasics/py/blob/master/pandas/6_handling_missing_data_replace/weather_data.csv

In [ ]:
df1 = pd.read_csv("weather_data.csv")  #/content/weather.csv

In [ ]:
df1

,day,temperature,windspeed,event
0,1/1/2017,32,6,Rain
1,1/2/2017,-99999,7,Sunny
2,1/3/2017,28,-99999,Snow
3,1/4/2017,-99999,7,0
4,1/5/2017,32,-99999,Rain
5,1/6/2017,31,2,Sunny
6,1/6/2017,34,5,0


In [ ]:
# pip3 install openpyxl
df1.to_excel('df_xl.xlsx', sheet_name = 'weather_data')

In [ ]:
# pip3 install xlrd
df2 = pd.read_excel('df_xl.xlsx')

In [ ]:
df2

,day,temperature,windspeed,event
0,1/1/2017,32,6,Rain
1,1/2/2017,35,7,Sunny
2,1/3/2017,28,2,Snow
3,1/4/2017,24,7,Snow
4,1/5/2017,32,4,Rain
5,1/6/2017,31,2,Sunny


In [ ]:
df2.to_csv('file.csv')

In [ ]:
df2.to_csv('file_noindex.csv', index = False)

In [ ]:
df_group = df2.groupby("event")

In [ ]:
df_group

In [ ]:
for temperature in df_group:
    print(temperature)

('Rain',         day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain)
('Snow',         day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow)
('Sunny',         day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
5  1/6/2017           31          2  Sunny)


In [ ]:
df_group.get_group('Rain')

,day,temperature,windspeed,event
0,1/1/2017,32,6,Rain
4,1/5/2017,32,4,Rain


In [ ]:
df_group.describe()

temperature                                               windspeed  \
            count  mean       std   min   25%   50%   75%   max     count   
event                                                                       
Rain          2.0  32.0  0.000000  32.0  32.0  32.0  32.0  32.0       2.0   
Snow          2.0  26.0  2.828427  24.0  25.0  26.0  27.0  28.0       2.0   
Sunny         2.0  33.0  2.828427  31.0  32.0  33.0  34.0  35.0       2.0   

                                                 
      mean       std  min   25%  50%   75%  max  
event                                            
Rain   5.0  1.414214  4.0  4.50  5.0  5.50  6.0  
Snow   4.5  3.535534  2.0  3.25  4.5  5.75  7.0  
Sunny  4.5  3.535534  2.0  3.25  4.5  5.75  7.0

In [ ]:
def hot_temp(x):
    return x > 30

In [ ]:
df2['hot_temp'] = df2['temperature'].apply(hot_temp)

In [ ]:
df2

,day,temperature,windspeed,event,hot_temp
0,1/1/2017,32,6,Rain,True
1,1/2/2017,35,7,Sunny,True
2,1/3/2017,28,2,Snow,False
3,1/4/2017,24,7,Snow,False
4,1/5/2017,32,4,Rain,True
5,1/6/2017,31,2,Sunny,True


In [ ]:
df2['hot_temp'] = df2['temperature'].apply(lambda x: x > 30)

In [ ]:
df2

,day,temperature,windspeed,event,hot_temp
0,1/1/2017,32,6,Rain,True
1,1/2/2017,35,7,Sunny,True
2,1/3/2017,28,2,Snow,False
3,1/4/2017,24,7,Snow,False
4,1/5/2017,32,4,Rain,True
5,1/6/2017,31,2,Sunny,True


In [ ]:
#pivot table

In [ ]:
df2.pivot_table(values = 'temperature', index = 'event', aggfunc = 'mean')

,temperature
event,
Rain,32
Snow,26
Sunny,33


In [ ]:
df2.pivot_table(columns = 'temperature')

temperature,24,28,31,32,35
hot_temp,False,False,True,True,True
windspeed,7,2,2,5,7


In [ ]:
help(pd.DataFrame.pivot_table)

Help on function pivot_table in module pandas.core.frame:

pivot_table(self, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All')
    Create a spreadsheet-style pivot table as a DataFrame. The levels in
    the pivot table will be stored in MultiIndex objects (hierarchical
    indexes) on the index and columns of the result DataFrame
    
    Parameters
    ----------
    values : column to aggregate, optional
    index : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types (except list).
        Keys to group by on the pivot table index.  If an array is passed,
        it is being used as the same manner as column values.
    columns : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types

##### groupby


In [ ]:
import pandas as pd
df=pd.read_csv("/content/weather_by_cities.csv")
df

,day,city,temperature,windspeed,event
0,1/1/2017,new york,32,6,Rain
1,1/2/2017,new york,36,7,Sunny
2,1/3/2017,new york,28,12,Snow
3,1/4/2017,new york,33,7,Sunny
4,1/1/2017,mumbai,90,5,Sunny
5,1/2/2017,mumbai,85,12,Fog
6,1/3/2017,mumbai,87,15,Fog
7,1/4/2017,mumbai,92,5,Rain
8,1/1/2017,paris,45,20,Sunny
9,1/2/2017,paris,50,13,Cloudy


In [ ]:
g=df.groupby("city")

In [ ]:
g.get_group("mumbai")["temperature"].max()

92

In [ ]:
g